[package]
name = 'Movelearn'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
my_address='0x82e106dfb8ab3760f1c89bd021e11576355665ea7f62d016d8cae926d9d32ace'